version: '3.5'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /var/mongodb/data:/data/db:rw
    ports:
      - 27017:27017
    restart: always
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge